### ISSUE TITLE
Oglaf comics is broken

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/ComicBookMaker#82]
```
~/Geekage/Comics/ComicBookMaker $ python comicbookmaker.py -c oglaf --log 10
DEBUG:root:Starting
DEBUG:root:update oglaf start
DEBUG:root:_create_output_dir oglaf start
DEBUG:root:_create_output_dir oglaf done
DEBUG:root:_load_db_from_file oglaf start
DEBUG:root:update oglaf last comic is http://oglaf.com/andrology/5/
DEBUG:root:get_next_comic oglaf starting 'get_next_comic' from http://oglaf.com/andrology/5/
DEBUG:root:get_content (url : http://oglaf.com/andrology/5/)
DEBUG:root:urlopen_wrapper (url : http://oglaf.com/andrology/5/)
DEBUG:root:get_next_link oglaf Next link is None
DEBUG:root:get_next_comic oglaf next/first comic will be None (url is http://oglaf.com/andrology/5/)
DEBUG:root:check_navigation oglaf about to check navigation from http://oglaf.com/andrology/5/
DEBUG:root:check_first_link oglaf about to check first link
DEBUG:root:get_content (url : http://oglaf.com)
DEBUG:root:urlopen_wrapper (url : http://oglaf.com)
oglaf : nothing new
Traceback (most recent call last):
  File "comicbookmaker.py", line 98, in <module>
    main()
  File "comicbookmaker.py", line 83, in main
    getattr(com, method_name)()
  File "ComicBookMaker/comic_abstract.py", line 225, in update
    for comic in cls.get_next_comic(last_comic):
  File "ComicBookMaker/comics.py", line 145, in get_next_comic
    cls.check_navigation(url)
  File "ComicBookMaker/comics.py", line 218, in check_navigation
    first = cls.check_first_link()
  File "ComicBookMaker/comics.py", line 166, in check_first_link
    firstlink = cls.get_first_comic_link()
  File ComicBookMaker/comics.py", line 1667, in get_first_comic_link
    return get_soup_at_url(cls.url).find("div", id="st").parent
AttributeError: 'NoneType' object has no attribute 'parent'

```

**Comment by SylvainDe** [comment]
0753e114f82e00c4ba7e3004272c1efad6292f87 is actually related to this.

**Comment by SylvainDe** [comment]
Fixed via https://github.com/SylvainDe/ComicBookMaker/issues/70
