### ISSUE TITLE
Yeti comics retrieval fails on page not found 404

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/ComicBookMaker#84]
```
ComicBookMaker$ python comicbookmaker.py --log 10 -c yeti
DEBUG:root:Starting
DEBUG:root:update yeti start
DEBUG:root:_create_output_dir yeti start
DEBUG:root:_create_output_dir yeti done
DEBUG:root:_load_db_from_file yeti start
DEBUG:root:update yeti last comic is http://theawkwardyeti.com/comic/hyperthyroidism-works/
DEBUG:root:get_next_comic yeti starting 'get_next_comic' from http://theawkwardyeti.com/comic/hyperthyroidism-works/
DEBUG:root:get_content (url : http://theawkwardyeti.com/comic/hyperthyroidism-works/)
DEBUG:root:urlopen_wrapper (url : http://theawkwardyeti.com/comic/hyperthyroidism-works/)
DEBUG:root:get_next_link yeti Next link is <link href="http://theawkwardyeti.com/comic/change/" rel="next"/>
DEBUG:root:get_next_comic yeti next/first comic will be <link href="http://theawkwardyeti.com/comic/change/" rel="next"/> (url is http://theawkwardyeti.com/comic/hyperthyroidism-works/)
DEBUG:root:get_next_comic yeti about to get http://theawkwardyeti.com/comic/change/ (<link href="http://theawkwardyeti.com/comic/change/" rel="next"/>)
DEBUG:root:get_content (url : http://theawkwardyeti.com/comic/change/)
DEBUG:root:urlopen_wrapper (url : http://theawkwardyeti.com/comic/change/)
Exception HTTP Error 404: Not Found for url http://theawkwardyeti.com/comic/change/
yeti : nothing new
Traceback (most recent call last):
  File "comicbookmaker.py", line 99, in <module>
    main()
  File "comicbookmaker.py", line 84, in main
    getattr(com, method_name)()
  File "/home/sylvain/Geekage/ComicBookMaker/comic_abstract.py", line 225, in update
    for comic in cls.get_next_comic(last_comic):
  File "/home/sylvain/Geekage/ComicBookMaker/comics.py", line 152, in get_next_comic
    soup = get_soup_at_url(url)
  File "/home/sylvain/Geekage/ComicBookMaker/urlfunctions.py", line 146, in get_soup_at_url
    content = get_content(url)
  File "/home/sylvain/Geekage/ComicBookMaker/urlfunctions.py", line 71, in get_content
    return urlopen_wrapper(url).read()
  File "/home/sylvain/Geekage/ComicBookMaker/urlfunctions.py", line 48, in urlopen_wrapper
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by SylvainDe** [comment]
Corresponding links:

 - http://theawkwardyeti.com/comic/change/

 - http://theawkwardyeti.com/comic/hyperthyroidism-works/

**Comment by SylvainDe** [comment]
The one after probably should be: http://theawkwardyeti.com/comic/hypothyroidism/ .

**Comment by SylvainDe** [comment]
I've contacted the author. If it gets fixed, I'l revert the workaround.

**Comment by SylvainDe** [comment]
The workaround is still required.
It is probably not going to change in the near future, let's close this.
