### ISSUE TITLE
Tapastic comic retrieval does not work

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/ComicBookMaker#85]
I haven't run the code for long so I don't know when this happened but it seems like a change on the website broke everything.

```
DEBUG:root:Starting
DEBUG:root:update 1111-tapa start
DEBUG:root:_create_output_dir 1111-tapa start
DEBUG:root:_create_output_dir 1111-tapa done
DEBUG:root:_load_db_from_file 1111-tapa start
DEBUG:root:update 1111-tapa last comic is None
DEBUG:root:urlopen_wrapper (url : https://tapastic.com/series/1111-Comics)
1111-tapa : nothing new
Traceback (most recent call last):
  File "comicbookmaker.py", line 106, in <module>
    main()
  File "comicbookmaker.py", line 91, in main
    getattr(com, method_name)()
  File "/home/user/ComicBookMaker/comic_abstract.py", line 224, in update
    for i, comic in enumerate(cls.get_next_comic(last_comic), 1):
  File "/home/user/ComicBookMaker/comics.py", line 278, in get_next_comic
    archive_elts = list(cls.get_archive_elements())
  File "/home/user/Geekage/ComicBookMaker/comics.py", line 5997, in get_archive_elements
    ][0]
IndexError: list index out of range

```

**Comment by SylvainDe** [comment]
Everything seems to be working fine now :)
